export const ErrorMsgs = {
	authRequired: 'Authorization required',
	emailExist: 'User email already exists',
	historyExist: 'History name already exists',
	historyNotFound: 'History not found',
	invalidAuthType: 'Invalid authorization type',
	invalidBody: 'Invalid body request',
	invalidEmailPasswd: 'Invalid email and/or password',
	invalidRefreshToken: 'Invalid refresh token',
	invalidSignature: 'Invalid signature',
	missingAll: 'Missing required fields: username, email and password',
	missingEmail: 'Missing required field: email',
	missingEmailAndPasswd: 'Missing required fields: email and password',
	missingParamId: 'Missing parameter id',
	missingPasswd: 'Missing required field: password',
	missingRefreshToken: 'Missing body field: refreshToken',
	missingUsername: 'Missing required field: username',
	missingUsernameAndEmail: 'Missing required fields: username and email',
	missingUsernameAndPasswd: 'Missing required fields: username and password',
	taskExist: 'Task name already exists',
	taskNotFound: 'Task not found',
	unableToDeleteHistory: 'Unable delete history because has tasks associated to it',
	unableToDeleteTask: 'Unable delete task because has timeTable associated to it',
	usernameExist: 'User username already exists',
	userNotFound: 'User not found',
};
