export const ErrorMsgs = {
	authRequired: 'Authorization required',
	emailExist: 'User email already exists',
	invalidAuthType: 'Invalid authorization type',
	invalidBody: 'Invalid body request',
	invalidEmailPasswd: 'Invalid email and/or password',
	invalidRefreshToken: 'Invalid refresh token',
	invalidSignature: 'Invalid signature',
	missingAll: 'Missing required fields: username, email and password',
	missingEmail: 'Missing required field: email',
	missingEmailAndPasswd: 'Missing required fields: email and password',
	missingParamId: 'Missing parameter ID',
	missingPasswd: 'Missing required field: password',
	missingRefreshToken: 'Missing body field: refreshToken',
	missingUsername: 'Missing required field: username',
	missingUsernameAndEmail: 'Missing required fields: username and email',
	missingUsernameAndPasswd: 'Missing required fields: username and password',
	usernameExist: 'User username already exists',
	userNotFound: 'User not found',
};
