version: '3'
services:
  api:
    command: npm start
    build: .
    volumes:
      - ./api:/api
    networks:
      - backend
    ports:
      - '3000:3000'

networks:
  backend:
    driver: bridge
